// ── CÓDIGOS DE OCORRÊNCIA BOPM / PMESP ─────────────────────
// Fonte: Formulário Anexo R.O - SMSU - 0000000-2019
// Arquivo isolado — não depende de nenhum outro módulo

var BOPM_CODIGOS = [
  { letra: "A", grupo: "CONTRA A PESSOA E A VIDA", codigos: [{"codigo": "A01", "descricao": "HOMICÍDIO CULPOSO"}, {"codigo": "A02", "descricao": "HOMICÍDIO DOLOSO"}, {"codigo": "A03", "descricao": "HOMICÍDIO TENTATIVA"}, {"codigo": "A04", "descricao": "ABORTO"}, {"codigo": "A05", "descricao": "AGRESSÃO"}, {"codigo": "A06", "descricao": "INFANTICÍDIO"}, {"codigo": "A07", "descricao": "PERICLITAÇÃO DE VIDA"}, {"codigo": "A08", "descricao": "ABANDONO"}, {"codigo": "A09", "descricao": "OMISSÃO DE SOCORRO"}, {"codigo": "A10", "descricao": "AMEAÇA"}, {"codigo": "A11", "descricao": "SEQUESTO E CÁRCERE PRIVADO"}, {"codigo": "A12", "descricao": "VIOLAÇÃO DE DOMICÍLIO"}, {"codigo": "A13", "descricao": "MAUS TRATOS À PESSOA"}, {"codigo": "A14", "descricao": "RIXA"}, {"codigo": "A15", "descricao": "CALÚNIA"}, {"codigo": "A16", "descricao": "DIFAMAÇÃO"}, {"codigo": "A17", "descricao": "INJÚRIA"}, {"codigo": "A18", "descricao": "CONSTRANGIMENTO ILEGAL"}, {"codigo": "A19", "descricao": "RACISMO"}, {"codigo": "A20", "descricao": "PEDIDO DE SOCORRO"}, {"codigo": "A21", "descricao": "ENCONTRO DE CADÁVER"}, {"codigo": "A22", "descricao": "SUICÍDIO"}, {"codigo": "A23", "descricao": "TENTATIVA DE SUICÍDIO"}, {"codigo": "A24", "descricao": "AFOGAMENTO EM CURSO"}, {"codigo": "A25", "descricao": "TORTURA"}, {"codigo": "A26", "descricao": "ABANDONO MATERIAL"}, {"codigo": "A27", "descricao": "ABANDONO INTELECTUAL"}, {"codigo": "A28", "descricao": "ENTREGA DE FILHO MENOR À PESSOA INIDÔNIA"}, {"codigo": "A29", "descricao": "SUBTRAÇÃO DE INCAPAZ"}, {"codigo": "A30", "descricao": "LESÃO CORPORAL/ AGRESSÃO CULPOSA"}, {"codigo": "A31", "descricao": "MORTE DE PESSOA"}, {"codigo": "A32", "descricao": "CONDUTAS DISCRIMINATÓRIAS"}] },
  { letra: "B", grupo: "CONTRA O PATRIM\u00d4NIO", codigos: [{"codigo": "B01", "descricao": "FURTO"}, {"codigo": "B02", "descricao": "FURTO TENTATIVA"}, {"codigo": "B03", "descricao": "ROUBO TENTATIVA"}, {"codigo": "B04", "descricao": "ROUBO"}, {"codigo": "B05", "descricao": "EXTORSÃO"}, {"codigo": "B06", "descricao": "POSSE/INVASÃO DE PROPRIEDADE"}, {"codigo": "B07", "descricao": "DANO MATERIAL"}, {"codigo": "B08", "descricao": "APROPRIAÇÃO INDÉBITA"}, {"codigo": "B09", "descricao": "ESTELIONATO FRAUDE"}, {"codigo": "B10", "descricao": "RECEPTAÇÃO"}, {"codigo": "B11", "descricao": "LATROCÍNIO"}, {"codigo": "B12", "descricao": "ALARME DISPARADO"}] },
  { letra: "C", grupo: "CONTRA A TRANQUILIDADE E OS MORTOS", codigos: [{"codigo": "C01", "descricao": "PERTURBAÇÃO DO SOSSEGO"}, {"codigo": "C02", "descricao": "CONDUTA INCONVENIENTE"}, {"codigo": "C03", "descricao": "EMBRIAGUEZ"}, {"codigo": "C04", "descricao": "DESINTELIGÊNCIA"}, {"codigo": "C05", "descricao": "AVERIGUAÇÃO DE ATITUDE SUSPEITA"}, {"codigo": "C06", "descricao": "PERTURBAÇÃO DE CERIMÔNIA FUNERÁRIA"}, {"codigo": "C07", "descricao": "VIOLAÇÃO DE SEPULTURA"}, {"codigo": "C08", "descricao": "DESTR/SUBTR/OCULT DE CADÁVER"}, {"codigo": "C09", "descricao": "VILIPÊNDIO DE CADÁVER"}, {"codigo": "C99", "descricao": "PANCADÃO/ FUNK/ESQUENTA"}] },
  { letra: "D", grupo: "CONTRA OS COSTUMES", codigos: [{"codigo": "D01", "descricao": "ESTUPRO"}, {"codigo": "D02", "descricao": "ESTUPRO TENTATIVA"}, {"codigo": "D03", "descricao": "ATO OBSCENO"}, {"codigo": "D04", "descricao": "ESCRITO OU OBJ. OBSCENO"}, {"codigo": "D05", "descricao": "ATENTADO VIOLENTO AO PUDOR"}, {"codigo": "D06", "descricao": "CORRUPÇÃO DE MENORES"}, {"codigo": "D07", "descricao": "RAPTO"}, {"codigo": "D08", "descricao": "EXPLORAÇÃO DO LENOCÍNIO"}, {"codigo": "D09", "descricao": "JOGOS DE AZAR"}, {"codigo": "D12", "descricao": "SERVIR BEBIDA ALCOÓLICA A INCAPAZ"}, {"codigo": "D13", "descricao": "IMPORTUNAÇÃO SEXUAL"}] },
  { letra: "E", grupo: "CONTRA A ADM.P\u00daBLICA", codigos: [{"codigo": "E01", "descricao": "PECULATO"}, {"codigo": "E02", "descricao": "CONCUSSÃO"}, {"codigo": "E03", "descricao": "CORRUPÇÃO"}, {"codigo": "E04", "descricao": "PREVARICAÇÃO"}, {"codigo": "E05", "descricao": "VIOLÊNCIA ARBITRÁRIA"}, {"codigo": "E06", "descricao": "USURPAÇÃO DE FUNÇÃO PÚBLICA"}, {"codigo": "E07", "descricao": "APOIO A ÓRGÃOS EXTERNOS"}, {"codigo": "E08", "descricao": "DESOBEDIÊNCIA"}, {"codigo": "E09", "descricao": "DESACATO"}, {"codigo": "E10", "descricao": "CONTRABANDO/ DESCAMINHO"}, {"codigo": "E11", "descricao": "ABUSO DE AUTORIDADE"}, {"codigo": "E13", "descricao": "RESISTÊNCIA"}] },
  { letra: "F", grupo: "COM ENTORPECENTES", codigos: [{"codigo": "F01", "descricao": "OCORRÊNCIA COM ENTORPECENTE"}] },
  { letra: "G", grupo: "COM PRESOS", codigos: [{"codigo": "G01", "descricao": "OCORRÊNCIA COM PRESO"}, {"codigo": "G02", "descricao": "COMUNICAÇÃO FALSA DE CRIME/TROTE"}] },
  { letra: "H", grupo: "CONTRA A ORGANIZA\u00c7\u00c3O DO TRABALHO", codigos: [{"codigo": "H01", "descricao": "GREVE"}, {"codigo": "H02", "descricao": "PIQUETE"}, {"codigo": "H03", "descricao": "TUMULTO"}, {"codigo": "H04", "descricao": "PASSEATA"}, {"codigo": "H05", "descricao": "SAQUE/ARRASTÃO"}, {"codigo": "H06", "descricao": "MANIFESTAÇÃO PÚBLICA"}] },
  { letra: "I", grupo: "CONTRA O MEIO AMBIENTE", codigos: [{"codigo": "I02", "descricao": "OCORRÊNCIA AMBIENTAL GCM"}, {"codigo": "I99", "descricao": "OUTRAS OCR AMBIENTAIS GCM"}] },
  { letra: "J", grupo: "CONTRA A INCOLUMIDADE, PAZ E F\u00c9 PUBLICA", codigos: [{"codigo": "J01", "descricao": "EXERCÍCIO ILEGAL DE PROFISSÃO/ ATIVIDADE"}, {"codigo": "J02", "descricao": "ENVENENAMENTO DE ÁGUA POTÁVEL"}, {"codigo": "J03", "descricao": "DETENÇÃO DE SUSPEITO"}, {"codigo": "J04", "descricao": "SUBVERSÃO /TERRORISMO"}, {"codigo": "J05", "descricao": "CRIME CONTRA A ECONOMIA POPULAR"}, {"codigo": "J06", "descricao": "FALSA IDENTIDADE"}, {"codigo": "J07", "descricao": "USO DE DOCUMENTO FALSO"}, {"codigo": "J08", "descricao": "FALSIDADE IDEOLÓGICA"}, {"codigo": "J09", "descricao": "ARMA DE FOGO (DISP.ACIDENTAL/INTEN./PORTE ILEGAL)"}, {"codigo": "J10", "descricao": "OCORRÊNCIA DE FALSIFICAÇÃO"}, {"codigo": "J11", "descricao": "ASSOCIAÇÃO CRIMINOSA"}, {"codigo": "J12", "descricao": "SOLTURA DE BALÕES/ FOGOS"}] },
  { letra: "L", grupo: "TR\u00c2NSITO", codigos: [{"codigo": "L01", "descricao": "VEÍCULO (ABAND./ AV./LOCAL./ PANE ELET./MEC./ SUBM.)"}, {"codigo": "L03", "descricao": "DIRIGIR VEÍCULO (DE FORMA PERIGOSA/ SEM HABILITAÇÃO)"}, {"codigo": "L06", "descricao": "INTERDIÇÃO DE VIA PÚBLICA"}, {"codigo": "L07", "descricao": "ATROPELAMENTO"}, {"codigo": "L08", "descricao": "ACID. DE TRÂNSITO COM VÍTIMA"}, {"codigo": "L09", "descricao": "ACID. DE TRÂNS SEM VÍTIMA"}, {"codigo": "L12", "descricao": "ACID. DE TRÂNSITO COM MOTO"}] },
  { letra: "M", grupo: "DE AUX\u00cdLIO AO P\u00daBLICO", codigos: [{"codigo": "M01", "descricao": "OCORRÊNCIA COM PESSOA (NEC.OBSERVAR COMPLEM.)"}, {"codigo": "M02", "descricao": "CHOQUE ELÉTRICO"}, {"codigo": "M03", "descricao": "MERGULHO /SALTO NA ÁGUA CAUSANDO TRAUMA"}, {"codigo": "M04", "descricao": "INSETO AGRESSIVO"}, {"codigo": "M05", "descricao": "OVERDOSE"}, {"codigo": "M06", "descricao": "INGESTÃO/INJEÇÃO/INALAÇÃO DE SUBSTÂNCIA"}, {"codigo": "M07", "descricao": "INTOXICAÇÃO POR EXPOSIÇÃO A GASES"}, {"codigo": "M08", "descricao": "LESÃO POR EXPOSIÇÃO A PRODUTOS PERIGOSOS (EX.EXPLOSÃO DE FOGOS)"}, {"codigo": "M09", "descricao": "QUEIMADURA"}, {"codigo": "M10", "descricao": "DESMORONAMENTO"}, {"codigo": "M11", "descricao": "AUXÍLIO A GESTANTE"}, {"codigo": "M12", "descricao": "DESAPARECIMENTO PESSOA"}, {"codigo": "M14", "descricao": "MAL SÚBITO"}, {"codigo": "M15", "descricao": "QUEDA PESSOA"}, {"codigo": "M19", "descricao": "PESSOA EM LOCAL DE RISCO"}] },
  { letra: "N", grupo: "INC\u00caNDIO E SALVAMENTO", codigos: [{"codigo": "N01", "descricao": "INCÊNDIO"}, {"codigo": "N02", "descricao": "EXPLOSÃO"}, {"codigo": "N03", "descricao": "SUPERAQUECIMENTO DE EQUIPAMENTO"}, {"codigo": "N04", "descricao": "VAZAMENTO"}, {"codigo": "N08", "descricao": "ACID. COM MEIO DE TRANSPORTE"}, {"codigo": "N10", "descricao": "DESABAMENTO / DESMORONAMENTO/SOTERRAMENTO"}, {"codigo": "N12", "descricao": "ANIMAL AGRESSIVO"}, {"codigo": "N13", "descricao": "OCORRÊNCIA COM OBJETO (NECESSÁRIO COMPLEMENTO)"}, {"codigo": "N14", "descricao": "INUNDAÇÃO / ENCHENTE"}, {"codigo": "N15", "descricao": "QUEDA (OBJETO/ NECESSITA COMPLEMENTO)"}, {"codigo": "N16", "descricao": "EMBARCAÇÃO EM SITUAÇÃO DE RISCO"}, {"codigo": "N19", "descricao": "MAUS TRATOS - PESSOA"}, {"codigo": "N21", "descricao": "OCORRÊNCIA COM ÁRVORE (QUEDA)"}, {"codigo": "N22", "descricao": "RISCO IMINENTE DE EXPLOSÃO"}, {"codigo": "N28", "descricao": "ANIMAL (FERIDO/ MORTO/ PEÇONHENTO/ MORTO NA VIA)"}] },
  { letra: "Z", grupo: "OCORR\u00caNCIAS N\u00c3O CADASTRADAS", codigos: [{"codigo": "Z01", "descricao": "EM VIA PÚBLICA, CALÇADA OU PRAÇA"}, {"codigo": "Z02", "descricao": "EM IMÓVEL PRIVADO"}, {"codigo": "Z03", "descricao": "EM IMÓVEL PÚBLICO"}, {"codigo": "Z04", "descricao": "EM EQUIPAMENTO DE CONCESSÃO DE SERVIÇO PÚBLICO"}, {"codigo": "Z05", "descricao": "NO MEIO AMBIENTE"}, {"codigo": "Z06", "descricao": "EM ESCOLA"}, {"codigo": "Z07", "descricao": "RELACIONADO À PROSTITUIÇÃO"}, {"codigo": "Z08", "descricao": "RELACIONADO À POPULAÇÃO DE RUA"}, {"codigo": "Z09", "descricao": "RELACIONADO A EVENTOS NÃO AUTORIZADOS"}, {"codigo": "Z10", "descricao": "RELACIONADO À ATIVIDADES IRREGULARES"}, {"codigo": "Z11", "descricao": "RELACIONADO À FALTA DE AUTORIZAÇÃO DE FUNCIONAMENTO"}, {"codigo": "Z99", "descricao": "OCORRÊNCIA NÃO CADASTRADA"}] },
];

function renderBopm(filtro) {
  var container = document.getElementById('bopmList');
  if (!container) return;
  var q = (filtro || '').toLowerCase().trim();
  var html = '';
  BOPM_CODIGOS.forEach(function(g) {
    var codigos = q
      ? g.codigos.filter(function(c) {
          return c.codigo.toLowerCase().includes(q) || c.descricao.toLowerCase().includes(q);
        })
      : g.codigos;
    if (!codigos.length) return;
    html += '<div class="bopm-grupo">';
    html += '<div class="bopm-grupo-header"><span class="bopm-letra">' + g.letra + '</span><span class="bopm-grupo-nome">' + g.grupo + '</span></div>';
    html += '<div class="bopm-codigos">';
    codigos.forEach(function(c) {
      html += '<div class="bopm-item"><span class="bopm-codigo">' + c.codigo + '</span><span class="bopm-descricao">' + c.descricao + '</span></div>';
    });
    html += '</div></div>';
  });
  if (!html) {
    html = '<div style="text-align:center;color:var(--text-muted);padding:2rem 0">Nenhum código encontrado.</div>';
  }
  container.innerHTML = html;
}

function initBopm() {
  renderBopm('');
  var input = document.getElementById('bopmSearch');
  if (input) input.addEventListener('input', function() { renderBopm(this.value); });
}
